fix: replace HOSTNAME with NODE_NAME variable
${HOSTNAME} variable is a system shell variable and is not
available to Jenkins directly. Replacing it with NODE_NAME
variable, which is internal to Jenkins. This should
prevent error "Failed to publish debug report:
groovy.lang.MissingPropertyException: No such property: HOSTNAME for class:
groovy.lang.Binding" from appearing.

Change-Id: I0f90079277ee0003c28a8b99da5eaaf673f14ade