Update Seed parameters for newer version of Jenkins
* Trim is a required option for newer versions of
  Jenkins (2.150.2).
* Satisfy sandbox(false) requirements for
  check_sandbox_parameter check in SuperSeed.
* Specify an absolute path for the jobs [1], otherwise
  seed fails to create those due to error:

  ERROR: Type of item "integration/airship/airship-in-a-bottle"
  does not match existing type, item type can not be changed

[1] https://github.com/daspilker/job-dsl-plugin/blob/job-dsl-1.49
    /job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin
    /LookupStrategy.java#L35-L36

Change-Id: Id21c7fe43b58691fcb50d86f25ba56d0d77abd82